TASK_TYPE: inference_i2vgen_entrance
batch_size: 1
chunk_size: 2
decoder_bs: 2
guide_scale: 9
max_frames: 32
round: 1
scale: 8
seed: 8888
target_fps: 16
test_list_path: data/test_list_for_i2vgen.txt
test_model: models/i2vgen_xl_00854500.pth
use_fp16: true
use_zero_infer: true
vldm_cfg: configs/i2vgen_xl_train.yaml
